name: Deploy Website

on:
  push:
    branches: [main]
    paths:
      - "website/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy website --project-name=whistype --branch=main
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_EMAIL: admin@wazeem.com
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
